apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: eu.gcr.io/kubernetes-13/php:latest
        ports:
        - containerPort: 80
